spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/asmar?serverTimezone=UTC
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: '@project.name@'
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: false
        use-sql-coments: false
        generate-statistics: false
        enable_lazy_load_no_trans: true
    show-sql: true
security:
  basic:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: info, health, configprops, logfile, metrics, env, loggers, httptrace, mappings, threaddump
    application:
  version: '@project.version@'
  timezone: ${user.timezone}

server:
  port: 8080
  ssl:
    enabled: false
  #servlet:
    #context-path: /asmar

email:
  exp: dadeil.dev1@gmail.com

stripe:
  api:
    key: 'sk_test_51KlsxnEzx1vEWKzbmR6PijX57tXhcK2rRWscyLPPOqs1lN6DsysQl0Q87TnqMpXvP2dVjH6eycJ8yJZE4UpaATZH00uYobnIpl'
  public:
    key: 'pk_test_51KlsxnEzx1vEWKzbQpgfVN30WvEb43IqUajNmJ2A7ZfYfOiqSoBcXhdHUfSX89gFSxxc5KB95TMC5k5z9IScdBEX00k8eKDmA3'

springdoc:
  api-docs:
    path: /api-docs